### PR TITLE
chore(i18n): adapt i18n branch to translate react views

### PR DESCRIPTION
**Pull request by davidvitora**
Work in Progress

Basically i'm updating the feature/i18n branch to use react-i18next in react components

### CODE REVIEW

**Comment by polonel** [comment]
I'm very open to this PR. I will need some time to review. How are you handling the Language selection?

**Comment by davidvitora** [comment]
@polonel Work in Progress, but i'm using i18next-browser-languagedetector

https://github.com/polonel/trudesk/pull/248/commits/b12bdee4da555e4336b142cee0ee77962d0f4f3c#diff-9a2b5613dd1a186eaf43d251f5d1451d

**Comment by polonel** [comment]
Since this is based on the i18n branch, I will go ahead and merge when you "finish" your commits. So we can have a single PR for the whole WIP.

**Comment by davidvitora** [comment]
I will be putting this on hold for some time, if you want you can pull this PR.

1/3 of the views are completed.

**Pull request merged**
