### PR TITLE
repair ticketSchema.statics.getTopTicketGroups()

### PR DESCRIPTION
**Pull request by tapvt**
When a group has been deleted, but the object ID is still present in the Ticket record, getTopTicketGroups() will fail. `t[i].group` will populate as null and attempting to access `t[i].group._id` causes the error. Check for a populated group before pushing data into array.

### CODE REVIEW

**Comment by polonel** [comment]
Thank you for your contribution. I will merge once I finish updating packages.
Can you tell me in what manner the group was deleted? It should prevent you from deleting a group that has tickets in the system. This is so historic tickets can still populate group fields for historic data. Was this a direct deletion of the group from the DB? Nevertheless the check you propose is important and should be there; I would just like to reproduce.

**Comment by tapvt** [comment]
Thanks for your hard work!

Y’know. It is really weird. I second-guessed myself after I sent the pull request, but the Trudesk install that I got the error from is a (brand new) production install. So, no the group was not removed via a direct modification to the database. I did create and delete various groups via web UI.

I will try to find steps to reproduce. I believe these tickets were soft-deleted, but am away from my main machine right now. Cannot verify.

Sounds like there’s code in place to either (1) prevent a group from being removed if existing ticket is tied to it, or (2) dis-associate a group from a ticket upon removal. I’d like to confirm it is functioning properly.

I’m just familiarizing myself with the codebase as of about 36 hours ago, so any direction is appreciated and I’m very happy to help out and PR back.

**Comment by polonel** [comment]
Thanks. 
Here is the check during the deletion of the group:
https://github.com/polonel/trudesk/blob/master/src/controllers/api/v1/groups.js#L245

**Comment by tapvt** [comment]
Thanks for the link to that, @polonel. I'd be tempted to move that logic to the model level as it is pretty much a matter of data consistency rather than business logic (for API level).

I think I'd prefer to "de-group" a given ticket rather than block the deletion of a given group, at least on the API level. On the GUI level, I think a notification that a group has tickets still related with an option to "de-group" would be an appropriate approach.

 I'll look more into it tomorrow. Looking forward to any input.

**Pull request merged**
